/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker */

#ifndef _Included_win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
#define _Included_win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeStop
  (JNIEnv *, jclass, jlong);

  /*
   * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
   * Method:    nativeSetFaceSize
   * Signature: (JI)V
   */
  JNIEXPORT void JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     win_intheworld_opencv4androiddemo_fd_DetectionBasedTracker
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_opencv4androiddemo_facedetect_DetectionBasedTracker_nativeDetect

  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
