
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_intheworld_slam_OrbSlam2Helper */

#ifndef _Included_orb_slam2_android_OrbSlam2Helper
#define _Included_orb_slam2_android_OrbSlam2Helper
#ifdef __cplusplus
extern "C" {
#endif

JavaVM* jvm;

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    initSystemWithParameters
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_slam_OrbSlam2Helper_initSystemWithParameters
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    startCurrentORB
 * Signature: (D[III)[I
 */
JNIEXPORT jintArray JNICALL Java_win_intheworld_slam_OrbSlam2Helper_startCurrentORB
        (JNIEnv *, jclass, jdouble, jintArray, jint, jint);

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    glesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_win_intheworld_slam_OrbSlam2Helper_glesInit
        (JNIEnv *, jclass);

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    glesRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_win_intheworld_slam_OrbSlam2Helper_glesRender
        (JNIEnv *, jclass);

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    glesResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_win_intheworld_slam_OrbSlam2Helper_glesResize
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     win_intheworld_slam_OrbSlam2Helper
 * Method:    readShaderFile
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT jintArray JNICALL Java_win_intheworld_slam_OrbSlam2Helper_startCurrentORBForCamera
        (JNIEnv *, jclass,jdouble, jlong,jint,jint);

#ifdef __cplusplus
}
#endif
#endif